# Generated by Django 3.0.3 on 2020-02-27 18:51

from django.db import migrations
import optimized_image.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200226_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=optimized_image.fields.OptimizedImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
