# Generated by Django 3.0.3 on 2020-03-05 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0009_auto_20200227_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='folgt',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='folgt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('user', 'folgt')},
        ),
        migrations.RemoveField(
            model_name='follower',
            name='follower',
        ),
    ]
